from pathlib import Path
from datetime import datetime, timedelta
import json
import time

from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

from process_attributor import get_process_info
from network_attributor import (
    get_remote_ips,
    get_network_locations
)
from local_network_attributor import (
    get_local_network_attribution
)
from threat_score import calculate_threat_score
from security_event import (
    create_security_event,
    print_security_event
)
from response_engine import respond_to_attack


# ============================================================
# PATHS AND CONFIGURATION
# ============================================================

HONEYTOKEN_DIR = Path("honeytokens").resolve()

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)

PID_FILE = LOG_DIR / "simulator.pid"

EVENT_LOG = LOG_DIR / "security_events.json"

NETWORK_CONTEXT_FILE = LOG_DIR / "network_context.json"

# Created by the controlled demo_server.py
NETWORK_ACCESS_FILE = LOG_DIR / "honeytoken_access.json"

# Prevent duplicate filesystem events
DEDUP_WINDOW = 1.0

# Network request must be recent enough to correlate
NETWORK_CORRELATION_WINDOW = timedelta(seconds=10)

# How frequently we check the network event file
NETWORK_ACCESS_CHECK_INTERVAL = 0.5

LAST_EVENTS = {}


# ============================================================
# LOAD PREVIOUS SECURITY EVENTS
# ============================================================

def load_logged_events():
    """
    Load previously logged security events.
    """

    if not EVENT_LOG.exists():
        return []

    try:
        with EVENT_LOG.open("r") as file:
            return json.load(file)

    except (json.JSONDecodeError, FileNotFoundError):
        return []


# ============================================================
# SAVE SECURITY EVENT
# ============================================================

def save_security_event(event):
    """
    Save a security event locally.
    """

    events = load_logged_events()

    events.append(event)

    with EVENT_LOG.open("w") as file:
        json.dump(
            events,
            file,
            indent=4
        )


# ============================================================
# NETWORK CONTEXT
# ============================================================

def load_network_context():
    """
    Load the most recent network request recorded
    by demo_server.py.
    """

    if not NETWORK_CONTEXT_FILE.exists():
        return None

    try:
        with NETWORK_CONTEXT_FILE.open("r") as file:
            return json.load(file)

    except (
        json.JSONDecodeError,
        FileNotFoundError
    ):
        return None


def get_correlated_network_context(event_time):
    """
    Determine whether a recent network request
    is likely responsible for the honeytoken event.
    """

    context = load_network_context()

    if not context:
        return None

    try:
        network_time = datetime.fromisoformat(
            context["timestamp"]
        )

    except (
        KeyError,
        ValueError
    ):
        return None

    time_difference = event_time - network_time

    if (
        timedelta(seconds=0)
        <= time_difference
        <= NETWORK_CORRELATION_WINDOW
    ):
        return context

    return None


# ============================================================
# CONTROLLED ATTACKER PROCESS
# ============================================================

def get_simulator_pid():
    """
    Get the PID of the controlled attacker simulation.
    """

    if not PID_FILE.exists():
        return None

    try:
        return int(
            PID_FILE.read_text().strip()
        )

    except (
        ValueError,
        OSError
    ):
        return None


def identify_process():
    """
    Identify the controlled attacker process.
    """

    pid = get_simulator_pid()

    if not pid:
        return None

    try:
        return get_process_info(pid)

    except Exception:
        return None


# ============================================================
# CONTROLLED NETWORK HONEYTOKEN EVENT
# ============================================================

def process_network_honeytoken_event(event_callback=None):
    """
    Process a honeytoken access event generated by
    the controlled network demo server.

    This event is produced by demo_server.py when the
    controlled network simulation accesses the FAKE
    honeytoken.

    It is not monitoring arbitrary remote systems.
    """

    if not NETWORK_ACCESS_FILE.exists():
        return

    try:
        with NETWORK_ACCESS_FILE.open("r") as file:
            network_event = json.load(file)

    except (
        json.JSONDecodeError,
        FileNotFoundError,
        OSError
    ):
        return

    # --------------------------------------------------------
    # DUPLICATE PROTECTION
    # --------------------------------------------------------

    event_id = (
        network_event.get("timestamp"),
        network_event.get("source_ip"),
        network_event.get("source_port")
    )

    if event_id in LAST_EVENTS:
        return

    LAST_EVENTS[event_id] = time.time()

    # --------------------------------------------------------
    # BASIC EVENT INFORMATION
    # --------------------------------------------------------

    file_path = Path(
        network_event.get(
            "file",
            HONEYTOKEN_DIR / "passwords.txt"
        )
    ).resolve()

    source_ip = network_event.get("source_ip")

    source_port = network_event.get("source_port")

    print("\n🚨 NETWORK HONEYTOKEN TRIGGERED")

    print(
        f"File: {file_path}"
    )

    print(
        f"Source IP: {source_ip}"
    )

    print(
        f"Source Port: {source_port}"
    )

    # ========================================================
    # SOURCE / LOCAL NETWORK ATTRIBUTION
    # ========================================================

    local_network_attribution = []

    print(
        "\n========== SOURCE ATTRIBUTION =========="
    )

    if source_ip:

        attribution = get_local_network_attribution(
            source_ip
        )

        local_network_attribution.append(
            attribution
        )

        print(
            f"Source IP: {source_ip}"
        )

        print(
            f"Source Port: {source_port}"
        )

        print(
            f"Hostname: "
            f"{attribution.get('hostname')}"
        )

        print(
            f"MAC: "
            f"{attribution.get('mac_address')}"
        )

        print(
            f"Vendor: "
            f"{attribution.get('vendor')}"
        )

        print(
            f"Subnet: "
            f"{attribution.get('subnet')}"
        )

        print(
            f"Network Type: "
            f"{attribution.get('network_type')}"
        )

    else:

        print(
            "No source IP available."
        )

    print(
        "========================================"
    )

    # ========================================================
    # PROCESS ATTRIBUTION
    # ========================================================

    process_info = identify_process()

    if process_info:

        print(
            "\n========== PROCESS ATTRIBUTION =========="
        )

        print(
            f"PID: "
            f"{process_info.get('pid')}"
        )

        print(
            f"Process: "
            f"{process_info.get('name', 'Unknown')}"
        )

        print(
            f"User: "
            f"{process_info.get('username', 'Unknown')}"
        )

        print(
            f"Command: "
            f"{process_info.get('command', 'Unknown')}"
        )

        print(
            "========================================="
        )

    else:

        # The network demo server itself is NOT the attacker.
        # This fallback simply identifies the event as coming
        # from the controlled network simulation.

        process_info = {
            "pid": None,
            "name": "network_attacker_simulation",
            "username": "Unknown",
            "command": "Controlled network simulation"
        }

        print(
            "\n[!] Controlled simulator PID unavailable."
        )

    # ========================================================
    # THREAT ANALYSIS
    # ========================================================

    threat_info = calculate_threat_score(
        str(file_path),
        process_info
    )

    print(
        "\n========== THREAT ANALYSIS =========="
    )

    print(
        f"Threat Score: "
        f"{threat_info['threat_score']}/100"
    )

    print(
        f"Severity: "
        f"{threat_info['severity']}"
    )

    print("Reasons:")

    for reason in threat_info["reasons"]:

        print(
            f" - {reason}"
        )

    print(
        "===================================="
    )

    # ========================================================
    # SECURITY EVENT
    # ========================================================

    security_event = create_security_event(
        file_path,
        "network_honeytoken_access",
        process_info
    )

    # Threat information
    security_event["threat_score"] = (
        threat_info["threat_score"]
    )

    security_event["threat_reasons"] = (
        threat_info["reasons"]
    )

    # Network information
    security_event["remote_ips"] = (
        [source_ip]
        if source_ip
        else []
    )

    security_event["network_locations"] = []

    security_event["network_context"] = (
        network_event
    )

    security_event["local_network_attribution"] = (
        local_network_attribution
    )

    # ========================================================
    # FLATTEN NETWORK FIELDS
    #
    # These are required by Backend/schemas.py
    # ========================================================

    security_event["source_ip"] = source_ip

    security_event["source_port"] = source_port

    if local_network_attribution:

        attribution = (
            local_network_attribution[0]
        )

        security_event["mac_address"] = (
            attribution.get("mac_address")
        )

        security_event["subnet"] = (
            attribution.get("subnet")
        )

        security_event["network_type"] = (
            attribution.get("network_type")
        )

    else:

        security_event["mac_address"] = None

        security_event["subnet"] = None

        security_event["network_type"] = None

    # ========================================================
    # DISPLAY SECURITY EVENT
    # ========================================================

    print_security_event(
        security_event
    )

    # ========================================================
    # ACTIVE RESPONSE
    # ========================================================

    response_result = respond_to_attack(
        security_event
    )

    print(
        "\n========== RESPONSE RESULT =========="
    )

    print(
        f"Contained: "
        f"{response_result.get('contained')}"
    )

    print(
        f"Process terminated: "
        f"{response_result.get('process_terminated')}"
    )

    print(
        "====================================="
    )

    # ========================================================
    # SAVE EVENT
    # ========================================================

    save_security_event(
        security_event
    )

    print(
        "\n[+] Security event saved to "
        f"{EVENT_LOG}"
    )

    # ========================================================
    # SEND TO BACKEND
    # ========================================================

    if event_callback:

        try:

            event_callback(
                security_event
            )

        except Exception as error:

            print(
                f"[!] Backend callback error: "
                f"{error}"
            )

    # ========================================================
    # REMOVE CONSUMED NETWORK EVENT
    #
    # Prevents the same demo event from being processed
    # again after restarting the agent.
    # ========================================================

    try:

        NETWORK_ACCESS_FILE.unlink()

    except OSError:

        pass


# ============================================================
# FILESYSTEM HONEYTOKEN HANDLER
# ============================================================

class HoneytokenHandler(
    FileSystemEventHandler
):

    def on_modified(self, event):

        self.check_honeytoken(
            event,
            "modified"
        )

    def on_created(self, event):

        self.check_honeytoken(
            event,
            "created"
        )

    def check_honeytoken(
        self,
        event,
        event_type
    ):

        # Ignore directories
        if event.is_directory:
            return

        file_path = Path(
            event.src_path
        ).resolve()

        # Make sure this is actually inside
        # the honeytoken directory.
        try:

            relative_path = file_path.relative_to(
                HONEYTOKEN_DIR
            )

        except ValueError:

            return

        # ====================================================
        # DUPLICATE FILESYSTEM EVENTS
        # ====================================================

        event_key = (
            str(file_path),
            event_type
        )

        current_time = time.time()

        if event_key in LAST_EVENTS:

            if (
                current_time
                - LAST_EVENTS[event_key]
                < DEDUP_WINDOW
            ):

                return

        LAST_EVENTS[event_key] = current_time

        # ====================================================
        # HONEYTOKEN TRIGGER
        # ====================================================

        print(
            "\n🚨 HONEYTOKEN TRIGGERED"
        )

        print(
            f"File: {file_path}"
        )

        print(
            f"Event: {event_type}"
        )

        print(
            f"Time: {datetime.now()}"
        )

        # ====================================================
        # PROCESS ATTRIBUTION
        # ====================================================

        process_info = identify_process()

        if process_info:

            print(
                "\n========== PROCESS ATTRIBUTION =========="
            )

            print(
                f"PID: "
                f"{process_info.get('pid')}"
            )

            print(
                f"Process: "
                f"{process_info.get('name', 'Unknown')}"
            )

            print(
                f"User: "
                f"{process_info.get('username', 'Unknown')}"
            )

            print(
                f"Command: "
                f"{process_info.get('command', 'Unknown')}"
            )

            print(
                "========================================="
            )

        else:

            process_info = {
                "pid": None,
                "name": "Unknown",
                "username": "Unknown",
                "command": "Unknown"
            }

            print(
                "\n[!] Process attribution unavailable."
            )

        # ====================================================
        # THREAT ANALYSIS
        # ====================================================

        threat_info = calculate_threat_score(
            str(file_path),
            process_info
        )

        print(
            "\n========== THREAT ANALYSIS =========="
        )

        print(
            f"Threat Score: "
            f"{threat_info['threat_score']}/100"
        )

        print(
            f"Severity: "
            f"{threat_info['severity']}"
        )

        print("Reasons:")

        for reason in threat_info["reasons"]:

            print(
                f" - {reason}"
            )

        print(
            "===================================="
        )

        # ====================================================
        # NETWORK ATTRIBUTION
        # ====================================================

        pid = process_info.get("pid")

        remote_ips = []

        network_locations = []

        if pid:

            remote_ips = get_remote_ips(
                pid
            )

            if remote_ips:

                network_locations = (
                    get_network_locations(
                        pid
                    )
                )

        print(
            "\n========== NETWORK ATTRIBUTION =========="
        )

        if remote_ips:

            for ip in remote_ips:

                print(
                    f"Remote IP: {ip}"
                )

        else:

            print(
                "No remote IP connections found."
            )

        print(
            "========================================="
        )

        # ====================================================
        # IP GEOLOCATION
        # ====================================================

        print(
            "\n========== IP GEOLOCATION =========="
        )

        if network_locations:

            for location in network_locations:

                print(
                    f"IP: "
                    f"{location.get('ip')}"
                )

                print(
                    f"Location: "
                    f"{location.get('location')}"
                )

                print(
                    f"ISP: "
                    f"{location.get('isp')}"
                )

        else:

            print(
                "No geographic location available."
            )

        print(
            "===================================="
        )

        # ====================================================
        # NETWORK REQUEST CORRELATION
        # ====================================================

        event_time = datetime.now()

        network_context = (
            get_correlated_network_context(
                event_time
            )
        )

        local_network_attribution = []

        print(
            "\n========== SOURCE ATTRIBUTION =========="
        )

        if network_context:

            source_ip = network_context.get(
                "source_ip"
            )

            source_port = network_context.get(
                "source_port"
            )

            print(
                f"Source IP: {source_ip}"
            )

            print(
                f"Source Port: {source_port}"
            )

            if source_ip:

                attribution = (
                    get_local_network_attribution(
                        source_ip
                    )
                )

                local_network_attribution.append(
                    attribution
                )

                print(
                    f"Hostname: "
                    f"{attribution.get('hostname')}"
                )

                print(
                    f"MAC: "
                    f"{attribution.get('mac_address')}"
                )

                print(
                    f"Vendor: "
                    f"{attribution.get('vendor')}"
                )

                print(
                    f"Subnet: "
                    f"{attribution.get('subnet')}"
                )

                print(
                    f"Network Type: "
                    f"{attribution.get('network_type')}"
                )

        else:

            print(
                "No correlated network request found."
            )

        print(
            "========================================"
        )

        # ====================================================
        # SECURITY EVENT
        # ====================================================

        security_event = create_security_event(
            file_path,
            event_type,
            process_info
        )

        security_event["threat_score"] = (
            threat_info["threat_score"]
        )

        security_event["threat_reasons"] = (
            threat_info["reasons"]
        )

        security_event["remote_ips"] = (
            remote_ips
        )

        security_event["network_locations"] = (
            network_locations
        )

        security_event["network_context"] = (
            network_context
        )

        security_event["local_network_attribution"] = (
            local_network_attribution
        )

        # ====================================================
        # FLATTEN NETWORK FIELDS
        # ====================================================

        security_event["source_ip"] = None

        security_event["source_port"] = None

        security_event["mac_address"] = None

        security_event["subnet"] = None

        security_event["network_type"] = None

        if network_context:

            security_event["source_ip"] = (
                network_context.get("source_ip")
            )

            security_event["source_port"] = (
                network_context.get("source_port")
            )

        if local_network_attribution:

            attribution = (
                local_network_attribution[0]
            )

            security_event["mac_address"] = (
                attribution.get("mac_address")
            )

            security_event["subnet"] = (
                attribution.get("subnet")
            )

            security_event["network_type"] = (
                attribution.get("network_type")
            )

        # ====================================================
        # DISPLAY
        # ====================================================

        print_security_event(
            security_event
        )

        # ====================================================
        # ACTIVE RESPONSE
        # ====================================================

        response_result = respond_to_attack(
            security_event
        )

        print(
            "\n========== RESPONSE RESULT =========="
        )

        print(
            f"Contained: "
            f"{response_result.get('contained')}"
        )

        print(
            f"Process terminated: "
            f"{response_result.get('process_terminated')}"
        )

        print(
            "====================================="
        )

        # ====================================================
        # SAVE EVENT
        # ====================================================

        save_security_event(
            security_event
        )

        print(
            "\n[+] Security event saved to "
            f"{EVENT_LOG}"
        )

        # ====================================================
        # BACKEND CALLBACK
        # ====================================================

        if self.event_callback:

            try:

                self.event_callback(
                    security_event
                )

            except Exception as error:

                print(
                    f"[!] Backend callback error: "
                    f"{error}"
                )

    # ========================================================
    # INITIALIZER
    # ========================================================

    def __init__(
        self,
        event_callback=None
    ):

        super().__init__()

        self.event_callback = (
            event_callback
        )


# ============================================================
# START WATCHER
# ============================================================

def start_watcher(
    event_callback=None
):

    print(
        "[*] Starting HoneyTrace filesystem watcher..."
    )

    print(
        f"[*] Monitoring: {HONEYTOKEN_DIR}"
    )

    print(
        f"[*] Monitoring network events: "
        f"{NETWORK_ACCESS_FILE}"
    )

    # ========================================================
    # FILESYSTEM WATCHER
    # ========================================================

    event_handler = HoneytokenHandler(
        event_callback=event_callback
    )

    observer = Observer()

    observer.schedule(
        event_handler,
        str(HONEYTOKEN_DIR),
        recursive=True
    )

    observer.start()

    # ========================================================
    # MAIN LOOP
    # ========================================================

    try:

        while True:

            # Check for a controlled network
            # honeytoken event.

            process_network_honeytoken_event(
                event_callback
            )

            time.sleep(
                NETWORK_ACCESS_CHECK_INTERVAL
            )

    except KeyboardInterrupt:

        print(
            "\n[*] Stopping HoneyTrace watcher..."
        )

        observer.stop()

    observer.join()


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    start_watcher()